#TODO
#Data: hvordan vil vi definere dette??
data_path: 'Data\CIFAR10'   

#Model. skal vi kunne definere forskellige archs?

run_dir: 'Weights\run_1'  # Directory where checkpoints are saved


# Training Parameters
batch_size: 50    # Batch size per GPU
lr: 0.001         # Learning rate
epochs: 50        # Number of iterations through the train set
num_workers: 2    # Number of subprocesses to use for loading data (in DataLoader)
shuffle: False    # Wether the training data is shuffled or not