data_path: 'Data\CIFAR10'   # Data Versioning



#Model. skal vi kunne definere forskellige archs?

run_dir: 'Weights\ddp_test_run1'  # Directory where checkpoints are saved


# Training Parameters
batch_size: 50    # Batch size per GPU
lr: 0.001         # Learning rate
epochs: 50        # Number of iterations through the train set
num_workers: 0    # Number of subprocesses to use for loading data (in DataLoader)
shuffle: False    # Wether the training data is shuffled or not


#WandB run name parameter
run_name: "MLOps"        # Name of the run for wandb logging

