name: Train and Validate New Model
on:
  push:
    branches:
      - train
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Run a script
        run: ./my-script.sh
      - name: Execute remote SSH commands using ssh key
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_GATEWAY }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_RSA_KEY }}
          script: |
            cat .github/workflows/scripts/train_and_valid.sh | ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_REMOTE }}
