name: Update Requirements

on:
  push:
    branches:
      - main

jobs:
  update-requirements:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for accurate commit tracking

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.11'  

    - name: Install pipreqs
      run: pip install pipreqs

    - name: Generate requirements.txt
      run: pipreqs . --force --mode no-pin  # Generate requirements.txt based on imports

    - name: Check for changes
      id: check-changes
      run: |
        git diff --exit-code requirements.txt || echo "changes_detected=true" >> $GITHUB_OUTPUT

    - name: Commit and push changes
      if: steps.check-changes.outputs.changes_detected == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add requirements.txt
        git commit -m "Auto-update requirements.txt"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}